ecommerce/app/urls.py
from django.conf.urls import include
from django.urls import path

from .views import *

app_name= 'app'

urlpatterns = [
    path('', HomeView.as_view(), name='homeview'),
    path('login', LoginView.as_view(), name='login'),
    path('signup', SignupView.as_view(), name='signup'),
    path('blog', BlogView.as_view(), name='blogview'),
    path('product', ProductView.as_view(), name='productview'),
    path('cart', CartView.as_view(), name='cartview'),
    path('logout', UserLogout.as_view(), name='logout'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

ecommerce/app/models.py
import uuid

from django.conf import settings
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

# Create your models here.
class BaseModel(models.Model):
	added = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now = True)

	class Meta:
		abstract=True


class MyUserManager(BaseUserManager):

    def create_superuser(self, username, password):
        user = self.model(email_address=email_address)
        user.set_password(password)
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_user(self, email_address, password=None, username=''):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email_address:
            raise ValueError('Users must have an Email Address')

        user = self.model(
            email_address=self.email_address,
            is_active=False,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, BaseModel):
    """
        User information
    """
    email_address = models.EmailField(
        "Email Address", unique=True, max_length=50, null=True, blank=True
    )
    name = models.CharField(
        "First Name", max_length=100, blank=True, null=True
    )
    uuid = models.UUIDField(
        default=uuid.uuid4, editable=False
    )
    is_superuser = models.BooleanField(
        "Super User", default=False
    )
    is_staff = models.BooleanField(
        "Staff", default=False
    )
    is_active = models.BooleanField(
        "Status", default=True
    )
    is_online = models.BooleanField(
        "User is online", default=False
    )

    objects = MyUserManager()
    USERNAME_FIELD = 'email_address'

    def has_perm(self, perm, obj=None):
        return self.is_staff

    def has_module_perms(self, app_label):
        return self.is_superuser

    def get_short_name(self):
        return self.name

    def __str__(self):
        return self.email_address

class Product(BaseModel):
    """Product Information"""
    product_name = models.CharField("Product Name", max_length=100)
    image = models.TextField("Image")
    type_of_product = models.CharField("Type of product",max_length=100)
    decription = models.TextField("Description")
    price = models.IntegerField("Product price")

    def __Str__(self):
        return self.product_name

class Cart(BaseModel):
	"""User Cart Information"""
	browser_finger = models.CharField("Browser finger print",max_length=225, null=True, blank=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Product,on_delete=models.CASCADE)
	total_product = models.IntegerField("Total product", default=0)

	def __str__(self):
		return self.user.email_address

class BrowserCart(BaseModel):
	"""Browser cart Information"""
	browser_finger = models.CharField("Browser finger print",max_length=225)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	total_product = models.IntegerField("Total product", default=0)
	def __str__(self):
		return self.user.browser_finger

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>E-Commerce</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>

    <![endif]-->
    <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/fingerprint.js' %}"></script>
	{% block head%}{% endblock %}
</head><!--/head-->

<body>
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +91 9654708686</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> nutan@yopmail.com</a></li>
								{% if request.user.is_authenticated %}
								<li><a href="#"><i class="fa fa-user" aria-hidden="true"></i>Welome {{request.user.name}} </a></li>
								{% endif %}
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="{% url 'app:homeview' %}"><img src="{% static 'images/home/e_logo2.png' %}" alt="" /></a>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="{% url 'app:homeview' %}"><i class="fa fa-user"></i> Home</a></li>
								<li><a href="javascript:void()" onclick="producthref()" id="id_product"><i class="fa fa-user"></i> Product</a></li>
								<li><a href="{% url 'app:blogview' %}"><i class="fa fa-user"></i> Blog</a></li>
								<li><a href="javascript:void()" onclick="getcart()" id="id_cart"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								<li><a href="{% url 'app:login' %}" class="active"><i class="fa fa-lock"></i> Login</a></li>
								<li><a href="{% url 'app:logout' %}" class="active"><i class="fa fa-lock"></i> Logout</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	{% block slide %} {% endblock %}


	{% block content %} {% endblock %}


	<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-Commerce</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe1.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2020</h2>
							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe2.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2202</h2>
							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe3.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2020</h2>
							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe4.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2020</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="{% static 'images/home/map.png' %}" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2020 E-Commerce Inc. All rights reserved.</p>
				</div>
			</div>
		</div>

	</footer><!--/Footer-->



    <script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
    	var fingerprint = new Fingerprint().get()
    	function producthref(){
    		var base_url = window.location['origin']
    		url = base_url+'/product?type=all'
    		localStorage.setItem("type", "all");
    		document.getElementById("id_product").href = url
    		return false
    	}
    	function getcart(){ 
            var base_url = window.location['origin']
            url = base_url+"/cart?fingerprint="+fingerprint
            document.getElementById("id_cart").href = url
    		return false
		}
    </script>
</body>
</html>

ecommerce/templates/blog.html
{% extends 'menu.html' %}
{% load static %}

{% block product %}
    <div class="col-sm-9">
            <div class="blog-post-area">
                <h2 class="title text-center">Latest From our Blog</h2>
                <div class="single-blog-post">
                    <h3>Girls Pink T Shirt arrived in store</h3>
                    <div class="post-meta">
                        <ul>
                            <li><i class="fa fa-user"></i> Mac Doe</li>
                            <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                            <li><i class="fa fa-calendar"></i> DEC 5, 2020</li>
                        </ul>
                        <span>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-half-o"></i>
                        </span>
                    </div>
                    <a href="">
                        <img src="{% static 'images/blog/blog-one.jpg' %}" alt="">
                    </a>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                </div>
                <div class="single-blog-post">
                    <h3>Girls Pink T Shirt arrived in store</h3>
                    <div class="post-meta">
                        <ul>
                            <li><i class="fa fa-user"></i> Mac Doe</li>
                            <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                            <li><i class="fa fa-calendar"></i> DEC 5, 2020</li>
                        </ul>
                        <span>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                        </span>
                    </div>
                    <a href="">
                        <img src="{% static 'images/blog/blog-two.jpg' %}" alt="">
                    </a>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                </div>
                <div class="single-blog-post">
                    <h3>Girls Pink T Shirt arrived in store</h3>
                    <div class="post-meta">
                        <ul>
                            <li><i class="fa fa-user"></i> Mac Doe</li>
                            <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                            <li><i class="fa fa-calendar"></i> DEC 5, 2020</li>
                        </ul>
                        <span>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                        </span>
                    </div>
                    <a href="">
                        <img src="{% static 'images/blog/blog-three.jpg' %}" alt="">
                    </a>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                </div>
            </div>
        </div>
{% endblock %}

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						{% if status %}
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
						{% endif %}
					</thead>
					<tbody>
						{% if status %}
							{%for data in data%}
								<form id="cartitem_{{data.cart_id}}" method="put">{% csrf_token %}
								
									<input type="hidden" name="fingerprint" id="fingerprint">
									<input type="hidden" name="id" id="id" value="{{data.cart_id}}">
								<tr>
									<td class="cart_product">
										<a href=""><img src="{% static '' %}{{data.image}}" alt=""></a>
									</td>
									<td class="cart_description">
										<h4><a href="">{{data.product_name}}</a></h4>
										<p>Web ID: {{data.cart_id}}</p>
									</td>
									<td class="cart_price">
										<p>${{data.price}}</p>
									</td>
									<td class="cart_quantity">
										<div class="cart_quantity_button">
											<a class="cart_quantity_up" href="javascript:void()" onclick="additem('{{data.cart_id}}')" id="add_item_{{data.cart_id}}"> + </a>
											<input class="cart_quantity_input" type="text" name="quantity" value="{{data.total_product}}" id="total_{{data.cart_id}}" autocomplete="off" size="2">
											<a class="cart_quantity_down" href="javascript:void()" onclick="removeitem('{{data.cart_id}}')" id="remove_item_{{data.cart_id}}"> - </a>
										</div>
									</td>
									<td class="cart_total">
										<p class="cart_total_price">${{data.total_price}}</p>
									</td>
									<td class="cart_delete">
										<a class="cart_quantity_delete" href="javascript:void()" onclick="deleteitem('{{data.cart_id}}')" id="delete_item_{{data.cart_id}}"><i class="fa fa-times"></i></a>
									</td>
								</tr>
								</form>
							{% endfor %}
						{% else %}
							<tr>
								<td>
								<div class="container text-center">
				                    <div class="logo-404">
				                        <a href="index.html"><img src="{% static 'images/home/e_logo2.png' %}" alt="" /></a>
				                    </div>
				                    <div class="content-404">
				                        <img src="{% static 'images/404/404.png' %}" class="img-responsive" alt="" />
				                        <h1><b>OPPS!</b> No Item found in cart</h1>
				                    </div>
				                </div>
				                </td>
							</tr>
						{% endif %}
					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->
	<script>
		var fingerprint = new Fingerprint().get()
		$('#fingerprint').val(fingerprint)
		base_url = window.location.href
		function additem(id){
			var form =$("#cartitem_"+id).serialize();
			form_list = form.split('&')[0].split("=")
			$.ajax({
				url: base_url+"&type=add&id="+id,
				type: 'put',
				headers: { "X-CSRFToken": form_list[1]},
				success: function (data) {
					if(data.status){
						alert("Item added successfully")
						window.location.replace(base_url)
	                    return false
					}else{
		                alert("Something wrong, try again!")
		                window.location.replace(base_url)
	                    return false
					}
					
				}
			});

		}
		function removeitem(id){
			var form =$("#cartitem_"+id).serialize();
			form_list = form.split('&')[0].split("=")
			$.ajax({
				url: base_url+"&type=decrease&id="+id,
				type: 'put',
				headers: { "X-CSRFToken": form_list[1]},
				success: function (data) {
					if(data.status){
						alert("Quantity of item decrease successfully")
						window.location.replace(base_url)
	                    return false
					}else{
		                alert("Something wrong, try again!")
		                window.location.replace(base_url)
	                    return false
					}
				}
			});
		}
		function deleteitem(id){
			var form =$("#cartitem_"+id).serialize();
			form_list = form.split('&')[0].split("=")
			$.ajax({
				url: base_url+'&id='+id,
				type: 'delete',
				headers: { "X-CSRFToken": form_list[1]},
				success: function (data) {
					if(data.status){
						alert("Item remove from cart successfully")
						window.location.replace(base_url)
	                    return false
					}else{
		                alert("Something wrong, try again!")
		                window.location.replace(base_url)
	                    return false
					}
				}
			});
		}
	</script>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block head%}

{% endblock %}
{% block content %}
	<section id="form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-4 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<h2>Login to your account</h2>
						<form action="{% url 'app:login' %}" id="loginuser" method="POST">
							{% csrf_token %}
							<input type="email" name="email_address" id="id_email_address" placeholder="Email Address" required/>
							<input type="password" name="password" id="id_password" placeholder="Password" required/>
							<input type="hidden" id="fingerprint" name="fingerprint">
							<button type="submit" id="userlogin" class="btn btn-default">Login</button>
						</form>
					</div><!--/login form-->
				</div>
				<div class="col-sm-1">
					<h2 class="or">OR</h2>
				</div>
				<div class="col-sm-4">
					<div class="signup-form"><!--sign up form-->
						<h2>New User Signup!</h2>
						<form  id="signupform" method="POST">
							{% csrf_token %}
							<input type="text" name="name" placeholder="Name" required/>
							<input type="email" name="email_address" placeholder="Email Address" required/>
							<input type="password" name="password" placeholder="Password" required/>
							<button type="submit" id="usersignup" onclick="Signup()" class="btn btn-default">Signup</button>
						</form>
					</div><!--/sign up form-->
				</div>
			</div>
		</div>
	</section><!--/form-->
	<script>
		var fingerprint = new Fingerprint().get()
		$('#fingerprint').val(fingerprint)
		var base_url = window.location['origin']
		function Signup(){
			var form = $("#signupform").serialize();
			$.ajax({
				url: base_url+'/signup',
				data: form,
				type: 'post',
				success: function (data) {
					alert(data.message)
					return true
				}
			});
		};
		function myFunction(message) {
		  alert(message);
		}
	</script>
{% endblock %}

ecommerce/templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block header-bottom %} {% endblock %}
{% block content %}
<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="javascript:void()" onclick="menhref()" id="id_product_men">Men</a></h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="javascript:void()" onclick="womenhref()" id="id_product_women">Women</a></h4>
								</div>
							</div>

                            <div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="javascript:void()" onclick="kidhref()" id="id_product_kid">Kids</a></h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="javascript:void()" onclick="househref()" id="id_product_house">Households</a></h4>
								</div>
							</div>
						</div><!--/category-products-->

						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well">
								<input type="radio" id="price1" name="price" onclick="pricefunction()" value="0-100">
								<label for="male">0-100</label><br>
								<input type="radio" id="price2" name="price" onclick="pricefunction()" value="101-500">
								<label for="male">101-500</label><br>
								<input type="radio" id="price3" name="price" onclick="pricefunction()" value="501-1500">
								<label for="male">501-1500</label><br>
								<input type="radio" id="price4" name="price" onclick="pricefunction()" value="1501-4000">
								<label for="male">1501-4000</label><br>
							</div>
						</div><!--/price-range-->

						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/shipping.jpg' %}" alt="" />
						</div><!--/shipping-->
					</div>
				</div>
				{% block product %}{% endblock %}
			</div>
		</div>
	</section>
	<script>
		// debugger;
		var base_url = window.location['origin']
		function menhref(){
    		url = base_url+'/product?type=men'
    		localStorage.setItem("type", "men");
    		document.getElementById("id_product_men").href = url
    		return false
    	}
    	function womenhref(){
    		url = base_url+'/product?type=women'
    		localStorage.setItem("type", "women");
    		document.getElementById("id_product_women").href = url
    		return false
    	}
    	function kidhref(){
    		url = base_url+'/product?type=kid'
    		localStorage.setItem("type", "kid");
    		document.getElementById("id_product_kid").href = url
    		return false
    	}
    	function househref(){
    		url = base_url+'/product?type=house'
    		localStorage.setItem("type", "house");
    		document.getElementById("id_product_house").href = url
    		return false
    	}
    	function pricefunction(){
    		type = localStorage.getItem("type");
    		if (!type){type="all"}
    		var price = document.getElementsByName("price")
    		for(i = 0; i < price.length; i++) { 
                if(price[i].checked) {
                	count = i+1
                	id = "price"+count.toString()
                	price=document.getElementById(id).value 
                }
            }
    		price_list = price.split('-');
    		url = base_url+'/product?type='+type+"&min_price="+price_list[0]+"&max_price="+price_list[1]
    		window.location.replace(url)
    	}
	</script>
{% endblock %}